version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mibase1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - liquibase-network
    volumes:
      - mysql-data:/var/lib/mysql

  liquibase:
    image: liquibase/liquibase
    command: >
      liquibase --driver=com.mysql.cj.jdbc.Driver
                --url=jdbc:mysql://mysql:3306/mibase1
                --username=user
                --password=password
                --changeLogFile=changelog/db.changelog-master.xml
                update
    depends_on:
      - mysql
    networks:
      - liquibase-network
    volumes:
      - ./changelog:/liquibase/changelog

volumes:
  mysql-data:

networks:
  liquibase-network:
    driver: bridge

